name: Auto-Merge Upstream
on:
  schedule:
    - cron: '0 * * * *'  # 每小时检查一次
  workflow_dispatch:     # 支持手动触发
jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/YangLeda/Userscripts-For-MilkyWayIdle.git
          git fetch upstream
      - name: Try to Merge
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main  # 你的默认分支
          git merge upstream/main --no-edit  # 尝试自动合并
          git push origin main
        shell: bash
